# Dependabot has native GitHub Actions support, to enable it on your GitHub repo
# all you need to do is add the .github/dependabot.yml file:
# https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"