{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-aws-iam-controller.serviceAccountName" . }}
  labels:
    {{- include "k8s-aws-iam-controller.labels" . | nindent 4 }}
  annotations:
    iam.aws.rustrial.org/trust-policy-statement: disable
    eks.amazonaws.com/role-arn: "{{ .Values.awsIamRole }}"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "k8s-aws-iam-controller.labels" . | nindent 4 }}
  name: "{{ include "k8s-aws-iam-controller.serviceAccountName" . }}-watch"
{{- if .Values.watchNamespace }}
  namespace: "{{ .Values.watchNamespace }}"
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
rules:
- apiGroups: ["iam.aws.rustrial.org"]
  resources: ["trustpolicystatements", "trustpolicystatements/status"]
  verbs: ["list", "get", "watch", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["list", "get", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "k8s-aws-iam-controller.labels" . | nindent 4 }}
  name: "{{ include "k8s-aws-iam-controller.serviceAccountName" . }}-storage"
{{- if .Values.storageNamespace }}
  namespace: "{{ .Values.storageNamespace }}"
kind: Role
{{- else }}
kind: ClusterRole
{{- end }}
rules:
- apiGroups: ["iam.aws.rustrial.org"]
  resources: ["roleusagepolicies", "roleusagepolicies/status"]
  verbs: ["list", "get", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "k8s-aws-iam-controller.labels" . | nindent 4 }}
  name: "{{ include "k8s-aws-iam-controller.serviceAccountName" . }}-watch"
{{- if .Values.watchNamespace }}
  namespace: "{{ .Values.watchNamespace }}"
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-aws-iam-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.watchNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: "{{ include "k8s-aws-iam-controller.serviceAccountName" . }}-watch"
---
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "k8s-aws-iam-controller.labels" . | nindent 4 }}
  name: "{{ include "k8s-aws-iam-controller.serviceAccountName" . }}-storage"
{{- if .Values.storageNamespace }}
  namespace: "{{ .Values.storageNamespace }}"
kind: RoleBinding
{{- else }}
kind: ClusterRoleBinding
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-aws-iam-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.storageNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: "{{ include "k8s-aws-iam-controller.serviceAccountName" . }}-storage"
{{- end}}