name: build

on:
  pull_request:
  push:
    branches:
      - main
      - "*"
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Format source
        run: "cargo +stable fmt"
      - name: Generate Custome Resource Definitions (CRDs)
        run: "cargo run --example gen-crds > charts/k8s-aws-iam-controller/crds/crds.yaml"
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
      - name: Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.7.0
        with:
          version: v0.17.0 # https://github.com/kubernetes-sigs/kind/releases
          node_image: "kindest/node:v1.25.3@sha256:f52781bc0d7a19fb6c405c2af83abfeb311f130707a0e219175677e366cc45d1"
          cluster_name: kind
      - name: Setup Helm
        uses: fluxcd/pkg/actions/helm@main
      - name: Setup Kubectl
        uses: fluxcd/pkg/actions/kubectl@main
      - name: Install from local image
        run: ./.github/install.sh
      - name: Run e2e tests
        run: ./.github/e2e-tests.sh
